import type { PunchExportLocale } from './punch-export-format'
import type { PunchIssueType } from './punch-issue-types'

export type PunchExportLabels = {
  reportInfo: string
  field: string
  value: string
  report: string
  reportName: string
  generated: string
  generatedBy: string
  screen: string
  screenValue: string
  punchTimeZone: string
  punchTimeZoneValue: string
  period: string
  dealers: string
  employee: string
  issueType: string
  liveStatus: string
  minHours: string
  maxHours: string
  search: string
  paymentType: string
  all: string
  until: string
  colEmployee: string
  colRoleDept: string
  colDealer: string
  colDate: string
  colPunchIn: string
  colBreakStart: string
  colBreakEnd: string
  colPunchOut: string
  colTimeWork: string
  colTimeBreak: string
  colPaymentType: string
  issueTypeLabels: Record<PunchIssueType, string>
  liveStatusLabels: Record<string, string>
  /** Fila "Error types" del Report Info. */
  errorTypes: string
  /** Nombre visible de cada codigo de TTK_PUNCH_WITH_ERROR_V2. */
  errorTypeNames: Record<1 | 2 | 3, string>
}

const EN: PunchExportLabels = {
  reportInfo: 'Report Info',
  field: 'Field',
  value: 'Value',
  report: 'Report',
  reportName: 'Punch Report (Individual)',
  generated: 'Generated',
  generatedBy: 'Generated by',
  screen: 'Screen',
  screenValue: 'Issues — Individual',
  punchTimeZone: 'Punch times zone',
  punchTimeZoneValue: 'America/New_York',
  period: 'Period',
  dealers: 'Dealers',
  employee: 'Employee',
  issueType: 'Issue type',
  liveStatus: 'Today status',
  minHours: 'Min hours',
  maxHours: 'Max hours',
  search: 'Search',
  paymentType: 'Payment Type',
  all: 'All',
  until: 'until',
  colEmployee: 'Employee',
  colRoleDept: 'Role / Dept',
  colDealer: 'Dealer',
  colDate: 'Date',
  colPunchIn: 'Punch In',
  colBreakStart: 'Break Start',
  colBreakEnd: 'Break End',
  colPunchOut: 'Punch Out',
  colTimeWork: 'Time Work',
  colTimeBreak: 'Time Break',
  colPaymentType: 'Payment Type',
  issueTypeLabels: {
    all: 'All',
    only_error: 'Only with errors',
    only_error_clockout: 'Without clock out',
    only_error_break: 'Break missing',
    only_error_20h: 'Shift 20h+',
    manual_punch: 'Manual punch',
    only_deletes: 'Deleted punches',
    without_salary: 'Without salary',
    only_fixed: 'Corrected punches',
  },
  errorTypes: 'Error types',
  errorTypeNames: {
    1: 'Without clock out',
    2: 'Break missing',
    3: 'Shift 20h+',
  },
  liveStatusLabels: {
    working: 'Working',
    on_lunch: 'On lunch',
    out: 'Out',
  },
}

const ES: PunchExportLabels = {
  reportInfo: 'Report Info',
  field: 'Campo',
  value: 'Valor',
  report: 'Reporte',
  reportName: 'Punch Report (Individual)',
  generated: 'Generado',
  generatedBy: 'Generado por',
  screen: 'Pantalla',
  screenValue: 'Issues — Individual',
  punchTimeZone: 'Zona de las ponchadas',
  punchTimeZoneValue: 'America/New_York',
  period: 'Período',
  dealers: 'Sucursales',
  employee: 'Empleado',
  issueType: 'Tipo de issue',
  liveStatus: 'Estado de hoy',
  minHours: 'Horas mínimas',
  maxHours: 'Horas máximas',
  search: 'Búsqueda',
  paymentType: 'Tipo de pago',
  all: 'Todos',
  until: 'hasta',
  colEmployee: 'Empleado',
  colRoleDept: 'Rol / Depto',
  colDealer: 'Sucursal',
  colDate: 'Fecha',
  colPunchIn: 'Entrada',
  colBreakStart: 'Inicio descanso',
  colBreakEnd: 'Fin descanso',
  colPunchOut: 'Salida',
  colTimeWork: 'Tiempo trabajado',
  colTimeBreak: 'Tiempo descanso',
  colPaymentType: 'Tipo de pago',
  issueTypeLabels: {
    all: 'Todos',
    only_error: 'Solo con errores',
    only_error_clockout: 'Sin salida',
    only_error_break: 'Sin descanso',
    only_error_20h: 'Turno 20h+',
    manual_punch: 'Ponchada manual',
    only_deletes: 'Ponchadas eliminadas',
    without_salary: 'Sin sueldo',
    only_fixed: 'Ponchadas corregidas',
  },
  errorTypes: 'Tipos de error',
  errorTypeNames: {
    1: 'Sin salida',
    2: 'Sin descanso',
    3: 'Turno 20h+',
  },
  liveStatusLabels: {
    working: 'Trabajando',
    on_lunch: 'En almuerzo',
    out: 'Fuera',
  },
}

export function punchExportLabels(locale: PunchExportLocale): PunchExportLabels {
  return locale === 'es' ? ES : EN
}

export function localeFromNavTemplate(typeNavTemplate: number | null | undefined): PunchExportLocale {
  return Number(typeNavTemplate) === 2 ? 'es' : 'en'
}
