// Tipos = DTOs del backend NestJS (src/srs/billing/dto/invoice-*.dto). Datos REALES.

export type InvoiceStatementTypeToken = 'wo' | 'ttk' | 'generic'

export interface InvoiceRow {
  id: number
  fullNro: string
  /** statement_type: 1-4 WO, 5 TTK, 6 Generic. */
  statementType: number
  estado: number
  wo?: string
  department?: string
  invoiceService?: string
  invoiceServiceSelRel?: string
  /** Raw GET_SERVICES_NAMES_BY_WO for Individual (type 1). */
  invoiceServicesByWo?: string
  invoiceNote?: string
  author?: string
  /** Generated by INVOICE_STATEMENT_SCHEDULE cron. */
  createdBySchedule?: boolean
  dealer?: string
  /** INVOICE_STATEMENT.id_dealer — the statement's own dealer, not the header filter. */
  idDealer?: number
  fechaCreate: string
  fechaDesde?: string
  fechaHasta?: string
  /** Las líneas de esta fila a precio (con el tax de las genéricas). */
  subtotal: number
  /** Configuración del descuento de la invoice (% o monto, según discountType). */
  discount?: number
  discountType?: number
  discountDetail?: string
  /** Descuento de esta fila en plata: subtotal − total (su parte del de la invoice). */
  discountAmount: number
  /** Plata neta de esta fila. La de saldo es el total de la invoice menos sus cobros. */
  total: number
  tax: number
  po?: string
  ro?: string
  sended: number
  emailsSended?: string
  lastSended?: string
  isBilled: number
  isPartialBilled: number
  notesCount?: number
  /** LOG_CHANGE rows linked to this statement. */
  logCount?: number
  idBilling?: number
  fechaPago?: string
  checkNumber?: string
  amount?: number
  nroBilled?: number | null
  idBillingWoRel?: number | null
  displayFullNro?: string
  /** Con el switch de parciales: el trabajo de esta fila que cae en el rango. */
  partialInvoiced?: number | null
  /** Con el switch de parciales: el período de la invoice no entra entero en el rango. */
  outsideRange?: boolean
}

export interface InvoiceSummary {
  count: number
  subtotal: number
  discount: number
  total: number
  deletedInList: number
  /** Total de las eliminadas del listado, una vez por invoice. null con Deleted = Hide. */
  deletedTotal?: number | null
  /** Con el switch de parciales: Partial Invoiced de todo el filtro, no de la página. */
  partialInvoiced?: number | null
}

/** Lo que se debe sin filtro de fecha (Outstanding AR), para la tarjeta del listado. */
export interface InvoiceOutstanding {
  outstandingAr: number
  openStatements: number
}

export interface InvoiceListResponse {
  results: InvoiceRow[]
  page: number
  pageSize: number
  hasMore: boolean
}

export interface InvoiceSummaryResponse {
  total: number
  summary: InvoiceSummary
}

export interface InvoiceDetailWoRow {
  id: number
  idStatement: number
  woNro?: string
  fechaAlta?: string
  vin?: string
  stockNumber?: string
  ro?: string
  po?: string
  department?: string
  service?: string
  observation?: string
  qty?: number
  price?: number
  isStatementFullBilled: number
  checkNumber?: string
  amount?: number
  fechaPago?: string
}

export interface InvoiceDetailGenericRow {
  id?: number
  idStatement: number
  description?: string
  genericQty?: number
  price?: number
  isStatementFullBilled: number
  checkNumber?: string
  amount?: number
  fechaPago?: string
  idAuthorTtk?: number
  rolName?: string
  departmentName?: string
  onlyTimecard: number
}

export interface InvoiceDetailResponse {
  idStatement: number
  statementType: number
  woRows: InvoiceDetailWoRow[]
  genericRows: InvoiceDetailGenericRow[]
}

export const INVOICE_PAGE_SIZE = 25

export interface InvoiceListParams {
  fechaDesde: string
  fechaHasta: string
  idDealer: string
  /** csv de 'wo' | 'ttk' | 'generic'. */
  types: string
  search?: string
  payed?: '0' | '1'
  sended?: '0' | '1'
  /** When true, include statements with total = 0. Default false (legacy not_show_cero). */
  includeZero?: boolean
  idDepartment?: string
  idInvoiceService?: string
  wo?: string
  roPo?: string
  stock?: string
  checkDate?: string
  checkNumber?: string
  idAuthor?: number
  idAuthorIn?: string
  authorsExclude?: 0 | 1
  createdBySystem?: 0 | 1
  exactMatch?: boolean
  dueOn?: boolean
  deleted?: 'hide' | 'only' | 'all'
  employeeWorkedIn?: string
  ignorePeriod?: boolean
  /** Suma las invoices que caen en parte en el rango y devuelve partialInvoiced por fila. */
  includePartial?: boolean
  /** WO por fecha de terminado en vez de por fecha de alta (Filter Date Completed). */
  filterDateDone?: boolean
  orderBy?: 'invoiceNro' | 'dateFrom'
  orderDir?: 'asc' | 'desc'
  page: number
  pageSize?: number
}

export type InvoiceLookupOption = {
  id: number
  label: string
  sublabel?: string
  thumbnailUuid?: string | null
  logoImg?: string | null
}

export interface InvoiceLookupResponse {
  results: InvoiceLookupOption[]
}

function buildInvoiceQuery(params: InvoiceListParams): string {
  const qs = new URLSearchParams({
    fechaDesde: params.fechaDesde,
    fechaHasta: params.fechaHasta,
    idDealer: params.idDealer,
    types: params.types,
    page: String(params.page),
    pageSize: String(params.pageSize ?? INVOICE_PAGE_SIZE),
  })
  if (params.search) qs.set('search', params.search)
  if (params.payed) qs.set('payed', params.payed)
  if (params.sended) qs.set('sended', params.sended)
  if (params.includeZero !== undefined) {
    qs.set('includeZero', params.includeZero ? 'true' : 'false')
  }
  if (params.idDepartment) qs.set('idDepartment', params.idDepartment)
  if (params.idInvoiceService) qs.set('idInvoiceService', params.idInvoiceService)
  if (params.wo) qs.set('wo', params.wo)
  if (params.roPo) qs.set('roPo', params.roPo)
  if (params.stock) qs.set('stock', params.stock)
  if (params.checkDate) qs.set('checkDate', params.checkDate)
  if (params.checkNumber) qs.set('checkNumber', params.checkNumber)
  if (params.idAuthor) qs.set('idAuthor', String(params.idAuthor))
  if (params.idAuthorIn) qs.set('idAuthorIn', params.idAuthorIn)
  if (params.authorsExclude === 1) qs.set('authorsExclude', '1')
  if (params.createdBySystem === 1) qs.set('createdBySystem', '1')
  if (params.exactMatch) qs.set('exactMatch', 'true')
  if (params.dueOn) qs.set('dueOn', 'true')
  if (params.deleted) qs.set('deleted', params.deleted)
  if (params.employeeWorkedIn) qs.set('employeeWorkedIn', params.employeeWorkedIn)
  if (params.ignorePeriod) qs.set('ignorePeriod', 'true')
  if (params.includePartial) qs.set('includePartial', 'true')
  if (params.filterDateDone) qs.set('filterDateDone', 'true')
  if (params.orderBy) qs.set('orderBy', params.orderBy)
  if (params.orderDir) qs.set('orderDir', params.orderDir)
  return `?${qs.toString()}`
}

export async function fetchInvoiceList(params: InvoiceListParams): Promise<InvoiceListResponse> {
  const res = await fetch(`/api/srs-kpis/billing/invoices${buildInvoiceQuery(params)}`, {
    cache: 'no-store',
  })
  if (!res.ok) {
    throw new Error(`Invoices (${res.status})`)
  }
  return res.json() as Promise<InvoiceListResponse>
}

export async function fetchInvoiceSummary(
  params: Omit<InvoiceListParams, 'page' | 'pageSize'> & { page?: number; pageSize?: number },
): Promise<InvoiceSummaryResponse> {
  const res = await fetch(
    `/api/srs-kpis/billing/invoices/summary${buildInvoiceQuery({
      ...params,
      page: params.page ?? 1,
      pageSize: params.pageSize ?? INVOICE_PAGE_SIZE,
    })}`,
    { cache: 'no-store' },
  )
  if (!res.ok) {
    throw new Error(`Invoice summary (${res.status})`)
  }
  return res.json() as Promise<InvoiceSummaryResponse>
}

/**
 * Lo que se debe sin filtro de fecha (toda la historia). Va por un endpoint aparte, sin fechas:
 * si tarda, el resto de la pantalla ya se ve y sólo la tarjeta queda cargando.
 */
export async function fetchInvoiceOutstanding(params: {
  idDealer: string
  includeZero?: boolean
}): Promise<InvoiceOutstanding> {
  const qs = new URLSearchParams({ idDealer: params.idDealer })
  if (params.includeZero !== undefined) {
    qs.set('includeZero', params.includeZero ? 'true' : 'false')
  }
  const res = await fetch(`/api/srs-kpis/kpis/collections/outstanding?${qs.toString()}`, {
    cache: 'no-store',
  })
  if (!res.ok) {
    throw new Error(`Outstanding AR (${res.status})`)
  }
  return res.json() as Promise<InvoiceOutstanding>
}

export type InvoiceDetailParams = {
  idBilling?: number
  payed?: '0' | '1'
  /** De la fila: separa dos filas del mismo cheque (TW641-3 y TW641-5). */
  nroBilled?: number | null
  /** De la fila: -1 cobro por línea, > 0 cobro de la invoice entera. */
  idBillingWoRel?: number | null
  idDepartment?: string
  idInvoiceService?: string
  stock?: string
}

export async function fetchInvoiceDetail(
  id: number,
  params: InvoiceDetailParams = {},
): Promise<InvoiceDetailResponse> {
  const qs = new URLSearchParams()
  if (params.idBilling != null) qs.set('idBilling', String(params.idBilling))
  if (params.payed === '0' || params.payed === '1') qs.set('payed', params.payed)
  if (params.nroBilled != null) qs.set('nroBilled', String(params.nroBilled))
  if (params.idBillingWoRel != null) qs.set('idBillingWoRel', String(params.idBillingWoRel))
  if (params.idDepartment) qs.set('idDepartment', params.idDepartment)
  if (params.idInvoiceService) qs.set('idInvoiceService', params.idInvoiceService)
  if (params.stock) qs.set('stock', params.stock)
  const q = qs.toString()
  const res = await fetch(
    `/api/srs-kpis/billing/invoices/${id}/detail${q ? `?${q}` : ''}`,
    { cache: 'no-store' },
  )
  if (!res.ok) {
    throw new Error(`Invoice detail (${res.status})`)
  }
  return res.json() as Promise<InvoiceDetailResponse>
}

function buildLookupQuery(params: {
  idDealer: string
  search?: string
  idDepartment?: string
  limit?: number
}): string {
  const qs = new URLSearchParams({ idDealer: params.idDealer })
  if (params.search) qs.set('search', params.search)
  if (params.idDepartment) qs.set('idDepartment', params.idDepartment)
  if (params.limit) qs.set('limit', String(params.limit))
  return `?${qs.toString()}`
}

export async function fetchInvoiceDepartments(params: {
  idDealer: string
  search?: string
  limit?: number
}): Promise<InvoiceLookupOption[]> {
  const res = await fetch(
    `/api/srs-kpis/billing/invoices/lookups/departments${buildLookupQuery(params)}`,
    { cache: 'no-store' },
  )
  if (!res.ok) throw new Error(`Invoice departments (${res.status})`)
  const data = (await res.json()) as InvoiceLookupResponse
  return data.results ?? []
}

export async function fetchInvoiceServices(params: {
  idDealer: string
  idDepartment?: string
  search?: string
  limit?: number
}): Promise<InvoiceLookupOption[]> {
  const res = await fetch(
    `/api/srs-kpis/billing/invoices/lookups/services${buildLookupQuery(params)}`,
    { cache: 'no-store' },
  )
  if (!res.ok) throw new Error(`Invoice services (${res.status})`)
  const data = (await res.json()) as InvoiceLookupResponse
  return data.results ?? []
}

export async function fetchInvoiceAuthors(params: {
  idDealer: string
  search?: string
  limit?: number
}): Promise<InvoiceLookupOption[]> {
  const res = await fetch(
    `/api/srs-kpis/billing/invoices/lookups/authors${buildLookupQuery(params)}`,
    { cache: 'no-store' },
  )
  if (!res.ok) throw new Error(`Invoice authors (${res.status})`)
  const data = (await res.json()) as InvoiceLookupResponse
  return data.results ?? []
}

export async function fetchInvoiceWorkers(params: {
  idDealer: string
  search?: string
  limit?: number
}): Promise<InvoiceLookupOption[]> {
  const res = await fetch(
    `/api/srs-kpis/billing/invoices/lookups/workers${buildLookupQuery(params)}`,
    { cache: 'no-store' },
  )
  if (!res.ok) throw new Error(`Invoice workers (${res.status})`)
  const data = (await res.json()) as InvoiceLookupResponse
  return data.results ?? []
}

export type InvoiceDistrictOption = InvoiceLookupOption & { dealerIds: number[] }

export async function fetchInvoiceDistricts(params: {
  search?: string
  limit?: number
}): Promise<InvoiceDistrictOption[]> {
  const qs = new URLSearchParams()
  if (params.search) qs.set('search', params.search)
  if (params.limit) qs.set('limit', String(params.limit))
  const q = qs.toString()
  const res = await fetch(
    `/api/srs-kpis/billing/invoices/lookups/districts${q ? `?${q}` : ''}`,
    { cache: 'no-store' },
  )
  if (!res.ok) throw new Error(`Invoice districts (${res.status})`)
  const data = (await res.json()) as { results?: InvoiceDistrictOption[] }
  return data.results ?? []
}
